name: C# Style Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  style-check:
    name: Проверка стиля C# (dotnet-format)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dotnet-format
        run: |
          dotnet tool install --global dotnet-format
          echo "${{ runner.tool_cache }}/dotnet-tools/bin" >> $GITHUB_PATH

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Find first *.csproj file
        id: find_proj
        run: |
          echo "PROJECT_PATH=$(find . -type f -name '*.csproj' | head -n1)" >> $GITHUB_ENV

      - name: Verify code style (dotnet-format)
        run: |
          if [ -z "$PROJECT_PATH" ]; then
            echo "No .csproj found, aborting style check."
            exit 1
          fi
          echo "Running dotnet format on $PROJECT_PATH"
          dotnet format "$PROJECT_PATH" --verify-no-changes --verbosity minimal
