name: Style Guide Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  style-check:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dotnet-format
        run: |
          dotnet tool install --global dotnet-format
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Find first *.sln file
        id: find_sln
        run: |
          SOLUTION_PATH=$(find . -type f -name '*.sln' | head -n1)
          echo "SOLUTION_PATH=$SOLUTION_PATH" >> $GITHUB_ENV

      - name: Restore NuGet packages
        run: dotnet restore "${{ env.SOLUTION_PATH }}"

      - name: Verify code style
        run: dotnet format "${{ env.SOLUTION_PATH }}" --verify-no-changes --verbosity minimal
